config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root "projects#index"
	
	resources :projects do
		resources :tickets
	end

end

app/models/project.rb
class Project < ActiveRecord::Base
	validates :name, presence: true
	has_many :tickets, dependent: :delete_all
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  belongs_to :author, class_name: "User"
  validates :title, presence: true
	validates :description, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :set_project, only: [:show, :edit, :update, :destroy]
	
	def index
		@projects = Project.all
	end
	
	def new
		@project = Project.new
	end
	
	def create
		@project = Project.new(project_params)
		if @project.save
			flash[:notice] = "Project has been created."
			redirect_to @project
		else
			flash.now[:alert] = "Project has not been created."
			render "new"
		end
	end
	
	def show
	end
	
	def edit
	end
	
	def update
		if @project.update(project_params)
			flash[:notice] = "Project has been updated."
			redirect_to @project
		else
			flash.now[:alert] = "Project has not been updated."
			render "edit"
		end
	end
	
	def destroy
		@project.destroy
		flash[:notice] = "Project has been deleted."
		redirect_to projects_path
	end
		
	private
	def project_params
		params.require(:project).permit(:name, :description)
	end
	
	def set_project
		@project = Project.find(params[:id])
		rescue ActiveRecord::RecordNotFound
			flash[:alert] = "The project you were looking" +
												" for could not be found."
			redirect_to projects_path
	end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
	before_action :set_project
	before_action :set_ticket, only: [:show, :edit, :update, :destroy]
	
	def new
		@ticket = @project.tickets.build
	end
	
	def create
		@ticket = @project.tickets.build(ticket_params)
		@ticket.author = current_user
		
		if @ticket.save
			flash[:notice] = "Ticket has been created."
			redirect_to [@project, @ticket]
		else
			flash.now[:alert] = "Ticket has not been created."
			render "new"
		end
	end
	
	def edit
	end
		
	def show
	end
	
	def update
		if @ticket.update(ticket_params)
			flash[:notice] = "Ticket has been updated."
			redirect_to [@project, @ticket]
		else
			flash.now[:alert] = "Ticket has not been updated."
			render "edit"
		end
	end
	
	def destroy
		@ticket.destroy
		flash[:notice] = "Ticket has been deleted."
		redirect_to @project
	end
	
private
	
	def ticket_params
		params.require(:ticket).permit(:title, :description)
	end	
	
	def set_project
		@project = Project.find(params[:project_id])
	end
	
	def set_ticket
		@ticket = @project.tickets.find(params[:id])
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title(*parts)
		unless parts.empty?
			content_for :title do
				(parts << "Ticketee").join(" - ")
			end
		end
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
		<% if content_for?(:title) %>
			<%= yield(:title) %>
		<% else %>
			Ticketee
		<% end %>
</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<%= link_to "Ticketee", root_path, class: "navbar-brand" %>
			</div>
			<ul class="nav navbar-nav">
				<li class="<%= "active" if current_page?("/") %>">
					<%= link_to "Home", root_path %>
				</li>
				
				<% unless user_signed_in? %>
					<li class="<%= "active" if current_page?("/users/sign_up") %>">
						<%= link_to "Sign up", new_user_registration_path %>
					</li>
					
					<li class="<%= "active" if current_page?("/users/sign_in") %>">
						<%= link_to "Sign in", new_user_session_path %>
					</li>
				<% end %>
			</ul>
			
			<% if user_signed_in? %>
				<ul class="nav navbar-nav navbar-right">
					<li class="navbar-text">
						Signed in as <%= current_user.email %>
					</li>
					<li>
						<%= link_to "Sign out", 
													destroy_user_session_path, method: :delete %>
					</li>
				</ul>
			<% end %>
		</div>
	</nav>
	
	<div class="container">
		<% flash.each do |key, message| %>
			<div class="alert alert-<%= key %>">
				<%= message %>
			</div>
		<% end %>
		<%= yield %>
	</div>
</body>
</html>

app/views/projects/_form.html.erb
<%= simple_form_for(project) do |f| %>
	<%= f.input :name %>
	<%= f.input :description %>
	
	<%= f.button :submit, class: "btn-primary" %>
<% end %>

app/views/projects/edit.html.erb
<div class="page-header">
	<h1>Edit Project</h1>
</div>
<%= render "form", project: @project %>

app/views/projects/index.html.erb
<div class="page-header">
	<h1>Projects</h1>
	
	<ul class="actions">
		<%= link_to "New Project", new_project_path, class: "new" %>
	</ul>
</div>
	
<div id="projects">
		<% @projects.each do |project| %>
			<h2><%= link_to project.name, project %></h2>
			<p><%= project.description %></p>
		<% end %>
</div>

app/views/projects/new.html.erb
<div class="page-header">
	<h1>New Project</h1>
</div>
<%= render "form", project: @project %>

app/views/projects/show.html.erb
<% title(@project.name, "Projects") %>
<div class="page-header">
	<h1><%= @project.name %></h1>
	<ul class="actions">
		<%= link_to "Edit Project", edit_project_path(@project), class: "edit" %>
		<%= link_to "Delete Project",
				project_path(@project),
				method: :delete,
				data: { confirm:"Are you sure you want to delete this project?"},
				class: "delete" %>
	</ul>
</div>

<div class="page-header">
	<h2>Tickets</h2>

	<ul class="actions">
		<li><%= link_to "New Ticket",
			new_project_ticket_path(@project),
			class: "new" %>
		</li>
	</ul>
</div>

<ul id="tickets">
	<% @project.tickets.each do |ticket| %>
		<li>
			#<%= ticket.id %> -
			<%= link_to ticket.title, [@project, ticket] %>
		</li>
	<% end %>
</ul>

app/views/tickets/_form.html.erb
<%= simple_form_for [project, ticket] do |f| %>
	<%= f.input :title %>
	<%= f.input :description %>
	
	<%= f.button :submit, class: "btn-primary" %>
<% end %>

app/views/tickets/edit.html.erb
<div class="page-header">
	<h1>
		Edit Ticket
		<small><%= @project.name %></small>
	</h1>
<%= render "form", project: @project, ticket: @ticket %>
</div>

app/views/tickets/new.html.erb
<div class="page-header">
	<h1>
		New Ticket
		<small><%= @project.name %></small>
	</h1>
</div>

<%= render "form", project: @project, ticket: @ticket %>

app/views/tickets/show.html.erb
<div id="ticket">
	<div class="page-header">
		<h1><%= @project.name %></h1>
	</div>

<div class="page-header">
	<h2><%= @ticket.title %></h2>
	<p id="author">
		Created by <%= @ticket.author.email %>, 
												<%= time_ago_in_words(@ticket.created_at) %> ago
	</p>
	<ul class="actions">
		<li><%= link_to "Edit Ticket", [:edit, @project, @ticket],
			class: "edit" %></li>
		<li><%= link_to "Delete Ticket", [@project, @ticket], method: :delete,
				data: { confirm: "Are you sure you want to delete this ticket?"},
				class: "delete" %></li>
	</ul>
</div>

	<%= simple_format(@ticket.description) %>
</div>